services:
  beyla-checkout:
    image: grafana/beyla:latest
    pid: "service:checkout"
    environment:
      - BEYLA_SERVICE_NAME=checkout
      - BEYLA_OPEN_PORT=8003
      - BEYLA_TRACE_PRINTER=text
      - BEYLA_BPF_ENABLE_CONTEXT_PROPAGATION=true
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
    privileged: true
  beyla-products:
    image: grafana/beyla:latest
    pid: "service:products"
    environment:
      - BEYLA_SERVICE_NAME=products
      - BEYLA_OPEN_PORT=8002
      - BEYLA_TRACE_PRINTER=text
      - BEYLA_BPF_ENABLE_CONTEXT_PROPAGATION=true
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
    privileged: true
  beyla-redis:
    image: grafana/beyla:latest
    pid: "service:redis"
    environment:
      - BEYLA_SERVICE_NAME=redis
      - BEYLA_OPEN_PORT=6379
      - BEYLA_TRACE_PRINTER=text
      - BEYLA_BPF_ENABLE_CONTEXT_PROPAGATION=true
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
    privileged: true

  beyla-frontproxy:
    image: grafana/beyla:latest
    pid: "service:frontproxy"
    environment:
      - BEYLA_SERVICE_NAME=frontproxy
      - BEYLA_OPEN_PORT=8000
      - BEYLA_TRACE_PRINTER=text
      - BEYLA_BPF_ENABLE_CONTEXT_PROPAGATION=true
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
    privileged: true